# Generated by Django 6.0.4 on 2026-04-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='ai_suggestion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Review', 'In Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=50),
        ),
    ]
