# Generated by Django 6.0.4 on 2026-04-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('samples_count', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('avatar_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('specialization', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Idle', 'Idle')], default='Active', max_length=20)),
                ('languages', models.ManyToManyField(related_name='experts', to='core.language')),
            ],
        ),
    ]
